### ISSUE TITLE
Bug - PostmasterFilter Import via CMD is not updating Filter

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny#527]
### Environment

- Server OS: Ubuntu
- Browser: Chrome
- Znuny version: 6.5.5

### Expected behavior

When altering a Postmaster Filter Konfiguration via `Admin:PostMasterFilter:Import` updates should be applied to the Filters.

### Actual behavior

Importing the configuration via CMD is not updating the Filter whereby crating a new filter works when changing the filter name. Since there seems to be no delete functionality creating a new filter every time is not a feasible solution.

### How to reproduce

1. Create a YAML file containing a valid filter config
```
---
- Match:
  - Key: From
    Value: INVALID-CUSTOMER2
  Name: Support - CustomerID test2
  Not:
  - Key: From
    Value: ~
  Set:
  - Key: X-OTRS-CustomerNo
    Value: test2
  StopAfterMatch: 0
```

2. Run Import
`sudo -uotrs /opt/otrs/bin/otrs.Console.pl Admin::PostMasterFilter::Import test2.yaml`

3. Alter YAML file:
```
---
- Match:
  - Key: From
    Value: VALID-CUSTOMER2
  Name: Support - CustomerID test2
  Not:
  - Key: From
    Value: ~
  Set:
  - Key: X-OTRS-CustomerNo
    Value: test2
  StopAfterMatch: 0
```

4. Run import again
`sudo -uotrs /opt/otrs/bin/otrs.Console.pl Admin::PostMasterFilter::Import test2.yaml`

5. Value is still the old one.

### Additional information

Updating existing filters was working fine at least in Znuny 6.0 where I previously used the add-on [ImportExportPostmasterFilter](https://opar.perl-services.de/dist/ImportExportPostmasterFilter). Since Updating to Znuny LTS this module is not available anymore so I tried to switch to the integrated version. However it seems that this issue has another origin since even when I install the previously used addon (making it install changing framework version in OPM) imports will not update Filters anymore.
